### ISSUE TITLE
Admin Notification Count is 0 in Listing

### ISSUE THREAD

**Issue by fareed543** [Snopzer/tspsc#1]
Steps to Reproduce :
1. Login to Admin Panel
2. Goto Notifications Page
3, In Listing the Count is 0, where it has some notifications in listing

![1 notification-count-issue](https://cloud.githubusercontent.com/assets/5229088/24461728/a2deabb6-14bf-11e7-9765-278294a25a38.png)

**Comment by wahd6** [comment]
Issue is fixed please recheck
